steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: Npm@1
  displayName: 'npm install'

- script: |
    echo "NIGHTLY enabled"
    node .azure-pipelines/common/nightlyVersionBump.js
    cat README.md >> README.nightly.md
    mv README.nightly.md README.md
  displayName: 'Tweak version for nightly'
  condition: eq(${{ parameters.nightly }}, true)

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run build
