steps:
- task: Npm@1
  displayName: 'Package'
  inputs:
    command: custom
    customCommand: run package

- task: CopyFiles@2
  displayName: 'Copy vsix to staging directory'
  inputs:
    Contents: '**/*.vsix'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: vsix'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: vsix
  condition: ne(variables['System.PullRequest.IsFork'], 'True')

- script: |
    set -e

    for f in $ARTIFACTS_DIR/vscode-docker-nightly*.vsix
    do
      echo Publishing $f
      npx vsce publish --packagePath $f --pat "$(marketplace_key)" --noVerify
    done
  displayName: 'Publish vscode-docker-nightly to marketplace'
  env:
    ARTIFACTS_DIR: $(build.artifactstagingdirectory)
  condition: and(succeeded(), eq(variables['publishnightly'], 'true'), eq(variables['nightly'], 'true'), eq(variables['build.sourcebranch'], 'refs/heads/master')) # Only if publishnightly and nightly are true, and it's master branch
